{% set name = "pyScss" %}
{% set version = "1.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8f35521ffe36afa8b34c7d6f3195088a7057c185c2b8f15ee459ab19748669ff

build:
  number: 4
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - pyscss=scss.tool:main
    - less2scss=scss.less2scss:main

requirements:
  build:
    - {{ compiler('c') }}
    - pcre
  host:
    - pcre
    - python
    - pip
  run:
    - python
    - six
    - enum34  # [py<34]
    - pathlib  # [py<34]
    - ordereddict  # [py<27]

test:
  imports:
    - scss
    - scss.extension
    - scss.extension.compass
    - scss.grammar

  commands:
    - pyscss --help
    - less2scss --help

about:
  home: http://github.com/Kronuz/pyScss
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: pyScss, a Scss compiler for Python
  description: |
    pyScss is a compiler for the Sass language, a superset of CSS3 that adds
    programming capabilities and some other syntactic sugar.
  doc_url: http://pyscss.readthedocs.org/en/latest/
  dev_url: https://github.com/Kronuz/pyScss

extra:
  recipe-maintainers:
    - stuertz
